spring.application.name=ai


llm.base-url=https://openrouter.ai/api
llm.provider=openrouter
llm.api-key=${OPENROUTER_API_KEY:}

spring.jackson.mapper.accept-case-insensitive-enums=true

resilience4j.circuitbreaker.instances.llm.sliding-window-size=5
resilience4j.circuitbreaker.instances.llm.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.llm.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.llm.wait-duration-in-open-state=10s

resilience4j.retry.instances.llm.max-attempts=3
resilience4j.retry.instances.llm.wait-duration=500ms
